version: '3.8'

services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    # args:
    #   DB_PASS: ${DB_PASS}
    #   DB_NAME: ${DB_NAME}
    #   DB_USER: ${DB_USER}
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - mynetwork
    env_file:
      - .env
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - mynetwork
  adminer:
    container_name: adminer
    build: ./requirements/adminer/
    networks:
      - mynetwork
    depends_on:
      - nginx
      - mariadb
networks:
  mynetwork:

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/root/Inception/srcs/home/hkhalil/db'
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/root/Inception/srcs/home/hkhalil/wp'