version: '3.8'

services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - mynetwork
    env_file:
      - var.env
    restart: on-failure
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb
    env_file:
      - var.env
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork
    restart: on-failure
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    env_file:
      - var.env
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - mynetwork
    restart: on-failure
  adminer:
    container_name: adminer
    build: ./requirements/adminer/
    image: adminer
    networks:
      - mynetwork
    depends_on:
      - nginx
    restart: on-failure
networks:
  mynetwork:

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hkhalil/data/db'
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hkhalil/data/wp'