version: '3.8'

services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - database
    volumes:
      - ../volumes/wp_volume/:/var/www/html
    ports:
      - 9000:9000
    networks:
      - mynetwork
    # environment:
    #   WORDPRESS_DB_HOST: mariadb
    #   WORDPRESS_DB_NAME: wordpress
    #   WORDPRESS_DB_USER: wordpress
    #   WORDPRESS_DB_PASSWORD: password

  database:
    container_name: mariadb
    build: ./requirements/mariadb/
    # environment:
    #   MYSQL_DATABASE: wordpress
    #   MYSQL_ROOT_PASSWORD: password
    #   MYSQL_USER: mysql
    #   MYSQL_PASSWORD: mysql_password
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - mynetwork

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    volumes:
      - ../volumes/wp_volume/:/var/www/html
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/db_volume'