version: '3.8'

services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - mynetwork
    # environment:
    #   WORDPRESS_DB_HOST: mariadb
    #   WORDPRESS_DB_NAME: wordpress
    #   WORDPRESS_DB_USER: wordpress
    #   WORDPRESS_DB_PASSWORD: password

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    # environment:
    #   MYSQL_DATABASE: wordpress
    #   MYSQL_ROOT_PASSWORD: password
    #   MYSQL_USER: mysql
    #   MYSQL_PASSWORD: mysql_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - mynetwork
  adminer:
    container_name: adminer
    build: ./requirements/adminer/
    networks:
      - mynetwork
    depends_on:
      - nginx
networks:
  mynetwork:

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/root/Inception/srcs/home/hkhalil/db'
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/root/Inception/srcs/home/hkhalil/wp'