version: '2'

services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - database
    volumes:
      - wordpress_data:/var/www/html
    restart: no
    ports:
      - 9000:9000
    networks:
      - mynetwork
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password

  database:
    container_name: mariadb
    build: ./requirements/mariadb/
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    restart: no
    ports:
      - 3306:3306
    networks:
      - mynetwork

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: no
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  wordpress_data:
  db_data: